### ISSUE TITLE
Two different background colors

### ISSUE THREAD

**Issue by sgomes** [atom/atom-dark-ui#69] opened 2017-02-10 13:28 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The atom-dark-ui theme uses two slightly different background colors on the editor: a lighter one that extends some space beyond the text on the line, and a darker one that extends to the rest of the editor edge. Different length lines thus have the lighter background going to different extents, producing an ugly staircase effect.

![image](https://cloud.githubusercontent.com/assets/409615/22828271/3cea1642-ef94-11e6-8221-5c958ff362f0.png)

### Steps to Reproduce

1. Choose "Atom Dark" UI theme in settings
2. Choose "Atom Dark" syntax theme in settings
3. Open an editor window with a variety of different line lengths
4. Observe the two distinct backgrounds

**Expected behavior:** For there to be a single background color that covers the entirety of the editor.

**Actual behavior:** There are two backgrounds colors, a lighter one, and a darker one.

**Reproduces how often:** Always.

### Versions

Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.0.390.gc69c2f50cf-goog

Running on macOS Sierra, Version 10.12.2.

### Additional Information

None.

**Comment by 50Wliu** [comment] 2017-02-10 17:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#12634. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-10 17:58 UTC
